using System.IO;
using LogicTests.CodeGeneration;
using Xunit;

namespace LogicTests
{
    public class TestGenerator
    {
        [Fact]
        public void EnsureUpdatedSources()
        {
            var generator = new CodeGenerator(Path.Combine(
                System.IO.Directory.GetCurrentDirectory(),
                @"..\..\..\Generated"));
            var wasUpToDate = generator.EnsureUpdatedSources();
            Assert.True(wasUpToDate, "Autogenerated tests had to be re-generated, please run the tests again!");
        }
    }
}